version: '3.3'

services:
  server:
    build: 
      context: .
      dockerfile: dockerFiles/nginx.dockerfile
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: dockerFiles/php.dockerfile
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
  composer:
    build: 
      context: ./dockerFiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build: 
      context: .
      dockerfile: dockerFiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    image: node
    working_dir: /var/www/html/
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html